version: 2

models:
  - name: stg_taxi_zones
    columns:
      - name: locationid
        tests:
          - unique
          - not_null
  - name: stg_data_dictionary
    columns:
      - name: field
        tests:
          - unique
          - not_null
  - name: stg_calendar_454
    columns:
      - name: data
        tests:
          - unique
          - not_null
